### PR TITLE
Transactional Support

### PR DESCRIPTION
**Pull request by autermann**
This PR adds two new modules:
* `transactional`: Support for transactional algorithm repositories
* `transactional-rest`: Extension of the OGC API - Processes with transactional support (see http://docs.opengeospatial.org/per/19-020r1.html#Annex-E, http://docs.opengeospatial.org/per/19-020r1.html#wps-server-52north)

~~The PR requires the [`javaps-rest`](https://github.com/autermann/javaps-rest) module to be in this repository, so we'll have to revisit this PR once @MartinPontius is done with his [work](https://github.com/autermann/javaps-rest/pull/26).~~

### CODE REVIEW

**Comment by matthesrieke** [comment]
@bpross-52n any news on this? @autermann is eager to support you in testing ;-)

**Comment by bpross-52n** [comment]
> @bpross-52n any news on this? @autermann is eager to support you in testing ;-)

I was busy with other projects. A quickstart or howto would be nice.

**Comment by autermann** [comment]
@matthesrieke Does the documentation Mohammed has written include something like that?

**Comment by matthesrieke** [comment]
@autermann @bpross-52n no, not on that level. the docu does not yet include transactional requests, it refers to static application packages as done in EOPAD.

**Comment by autermann** [comment]
@matthesrieke [javaPS-docker-backend](https://github.com/52North/javaPS-docker-backend) does build if you build this branch before...

**Comment by matthesrieke** [comment]
@autermann great, thanks for checking. I have provided @mohammedsaad with the instructions on testing and documentation!

**Comment by matthesrieke** [comment]
@autermann @bpross-52n I checked in with @mohammedsaad and he will create a PR against `autermann:feature/transactional` which will include the documentation. I just tested it locally with his examples and all looks good.

**Comment by matthesrieke** [comment]
As we decided to use the Wiki for documentation, Mohammed has put the documentation there:

https://github.com/52North/javaPS/wiki/Transactional-Process-API

**Pull request merged**
