### PR TITLE
merge eclipse related workarounds

### PR DESCRIPTION
**Pull request by matthesrieke**

### CODE REVIEW

**Comment by bpross-52n** [comment]
The travis build fails. Please fix this and next time check before merging. Thanks.

**Comment by matthesrieke** [comment]
True, will consider that in the future.

**Comment by matthesrieke** [comment]
I checked again locally (as I was quite sure that I did a local build), the build passes on my dev machine without enforcer issues. @autermann @bpross-52n any clue? I used the same command as in the travis config (`mvn -fae -U -B clean install`).

**Comment by autermann** [comment]
Try `CI=true` or `-P check`

**Comment by matthesrieke** [comment]
still, why are the rules not checked on a normal build (I know the profile is in the parents ;-) )? this will confuse developers as the build passes locally but breaks in travis.

**Pull request merged**
